name: ErfanGSI-build

on:
  workflow_dispatch:
    inputs:
      ROM_URL:
        description: 'Direct link/直链'
        required: true
        default: 'https://www.dropbox.com/scl/fi/3c0c6yc3mw4bhyc8p1b47/Nothing.7z?rlkey=59aippzub2c08sp3nt8hd8vdd&st=dkrelby4&dl=1'
      REPACK_NAME:
        description: 'Compressed name/打包名称'
        required: true
        default: 'NothingGSI.7z'
      ROM_TYPE:
        description: 'ROM type/ROM 类型'
        required: true
        default: 'Generic'
      ALI:
        description: 'Aliyun Upload Flag (1=skip compression)'
        required: false
        default: '0'
#env:
#  TELEGRAM_TO: 7194493949
#  TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}

jobs:
  build_tosasitill_GSI:
    runs-on: ubuntu-22.04

    steps:
      - name: 获取源代码
        uses: actions/checkout@main
        with:
          path: ErfanGSIs

      - name: 获取变量
        run: |
          echo "BUILD_TIME=$(date +%s | md5sum | awk '{print substr($1,1,10)}')" >> $GITHUB_ENV
          echo "BUILD_sTIME=$(TZ=Asia/Shanghai date -d @$(date +%s) +'%Y-%m-%d %H:%M:%S %Z')" >> $GITHUB_ENV

#      - name: 发送 Telegram 提醒消息 1/2
#        uses: appleboy/telegram-action@master
#        with:
#         to: 1214932938
#         token: ${{ secrets.TELEGRAM_TOKEN }}
#         message: tosasitill GSI 开始构建！
#                      构建开始时间：${{ env.BUILD_sTIME }}
#                         提交链接：${{ github.event.inputs.ROM_URL }}
#                             提交 GSI 类型：${{ github.event.inputs.ROM_TYPE }}

      - name: 配置环境‌‌
        run: |
          sudo apt install -y git wget git gzip unzip curl axel aria2 zstd rename p7zip-full pigz
          sudo apt update
          sudo apt install -y python3 python3-pip python3-setuptools
          python3 -m pip install --upgrade pip
          sudo ln -s $(which pip3) /usr/bin/pip || true
          sudo apt install -y git wget gzip unzip curl axel aria2 zstd rename p7zip-full pigz


      - name: 获取 ErfanGSI 工具
        uses: actions/checkout@main
        with:
          repository: tosasitill/erfanSGSI
          path: ErfanGSIs

      - name: Fix setup.sh pip -> pip3
        run: |
          sed -i 's/\bpip\b/pip3/g' $GITHUB_WORKSPACE/ErfanGSIs/setup.sh

      - name: 更换 777 权限
        run: |
          sudo chmod 777 -R $GITHUB_WORKSPACE/ErfanGSIs

      - name: 修复意外退出
        run: |
              sed -i 's/\|\| exit 1//g' ErfanGSIs/url2GSI.sh
              sed -i 's/exit 1//g' ErfanGSIs/url2GSI.sh

      - name: 建立并配置 ErfanGSI 工具所需环境
        run: |
          sudo sed -i 's/USE_MIRROR_FOR_PIP\=true/USE_MIRROR_FOR_PIP\=false/' $GITHUB_WORKSPACE/ErfanGSIs/setup.sh
          sudo bash $GITHUB_WORKSPACE/ErfanGSIs/setup.sh
          java -version
          pip3 install aligo

      - name: 下载 ROM 并制作 GSI
        run: |
          cd ${{ github.workspace }}/ErfanGSIs/
          sudo bash ./url2GSI.sh --aonly "${{ github.event.inputs.ROM_URL }}" "${{ github.event.inputs.ROM_TYPE }}"

      - name: 压缩 GSI
        if: ${{ github.event.inputs.ALI }} != '1'
        run: |
          cd $GITHUB_WORKSPACE/ErfanGSIs
          pwd
          7za a -mmt16 -t7z -r tosasitillGSI0202_${{ github.event.inputs.REPACK_NAME }} output/*
          ls "tosasitillGSI0202_${{ github.event.inputs.REPACK_NAME }}"
          mkdir upload_ab
          ls upload_ab
          if [ $(ls -l tosasitillGSI0202_${{ github.event.inputs.REPACK_NAME }} | awk '{print $5}') -gt 2147483647 ]; then tar cvzpf - tosasitillGSI0202_${{ github.event.inputs.REPACK_NAME }} | split -d -b 1024m - upload_ab/tosasitillGSI0202_${{ github.event.inputs.REPACK_NAME }}; else mv tosasitillGSI0202_${{ github.event.inputs.REPACK_NAME }} upload_ab/tosasitillGSI0202_${{ github.event.inputs.REPACK_NAME }}; fi

#      - name: 发送 Telegram 提醒消息 2/2
#        uses: appleboy/telegram-action@master
#        with:
#            to: 1214932938
#            token: ${{ secrets.TELEGRAM_TOKEN }}
#            message: tosasitill GSI 构建成功!
#              构建 GSI 详细信息如下！
#            document: ${{ github.workspace }}/ErfanGSIs/build_info.txt

      - name: 上传至 Github Releases
        if: ${{ github.event.inputs.ALI }} != '1'
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "${{ github.workspace }}/ErfanGSIs/upload_ab/*"
          tag: "${{ github.event.inputs.REPACK_NAME }}_${{ env.BUILD_TIME }}"
          bodyFile: "${{ github.workspace }}/ErfanGSIs/output/build_info.txt"
          token: ${{ secrets.GITHUB_TOKEN }}
